# Generated by Django 5.0.12 on 2025-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default='categorias/default.jpg', null=True, upload_to='categorias/', verbose_name='Imagen de categoría'),
        ),
    ]
